
package org.simple.engine.service.endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://endpoint.service.engine.simple.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.simple.engine.service.endpoint.Document>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentsByTokens", targetNamespace = "http://endpoint.service.engine.simple.org/", className = "org.simple.engine.service.endpoint.GetDocumentsByTokens")
    @ResponseWrapper(localName = "getDocumentsByTokensResponse", targetNamespace = "http://endpoint.service.engine.simple.org/", className = "org.simple.engine.service.endpoint.GetDocumentsByTokensResponse")
    @Action(input = "http://endpoint.service.engine.simple.org/Server/getDocumentsByTokensRequest", output = "http://endpoint.service.engine.simple.org/Server/getDocumentsByTokensResponse")
    public List<Document> getDocumentsByTokens(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.simple.engine.service.endpoint.Document
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://endpoint.service.engine.simple.org/", className = "org.simple.engine.service.endpoint.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://endpoint.service.engine.simple.org/", className = "org.simple.engine.service.endpoint.GetResponse")
    @Action(input = "http://endpoint.service.engine.simple.org/Server/getRequest", output = "http://endpoint.service.engine.simple.org/Server/getResponse")
    public Document get(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "put", targetNamespace = "http://endpoint.service.engine.simple.org/", className = "org.simple.engine.service.endpoint.Put")
    @ResponseWrapper(localName = "putResponse", targetNamespace = "http://endpoint.service.engine.simple.org/", className = "org.simple.engine.service.endpoint.PutResponse")
    @Action(input = "http://endpoint.service.engine.simple.org/Server/putRequest", output = "http://endpoint.service.engine.simple.org/Server/putResponse")
    public void put(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Document arg1);

}
